---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: angularappdeployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: angular
 template:
  metadata:
   name: angular
   labels:
     app: angular
  spec:
    containers:
    - name: angularcontainer
      image: srinath999/angular-app
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: angularsvc
spec:
  type: LoadBalancer
  selector:
   app: angular
  ports:
   - port: 80
     targetPort: 80
...
